# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-15 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='awehomeinfos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refer', models.CharField(max_length=100)),
                ('awehome', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
