# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-15 03:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='awehomeinfos',
            old_name='add_date',
            new_name='time_now',
        ),
    ]
