# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-02-16 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0002_auto_20190215_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='awehomeinfos',
            name='web_site',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
